permissions:
  pages: write
  id-token: write
  contents: read

name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'  # Change this to your target .NET version

      - name: Restore dependencies
        run: dotnet restore
      - name: Build and test
        run: |
          cd BlazorTest
          dotnet build
          dotnet test ../BlazorTest.Tests

      - name: Build the project
        if: success()
        run: dotnet publish -c Release -o output

      - name: Upload GitHub Pages artifact
        if: success()
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: output/wwwroot
          # Artifact name
      
          # Path of the directory containing the static assets.
          # Duration after which artifact will expire in days.

      - name: Deploy to GitHub Pages
        if: success()
        uses: actions/deploy-pages@v4.0.5
