permissions:
  pages: write
  id-token: write
  contents: read

name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --logger trx --results-directory TestResults

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'  # Change this to your target .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet publish -c Release -o output

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: output/wwwroot
          # Artifact name
      
          # Path of the directory containing the static assets.
          # Duration after which artifact will expire in days.

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
